#!/bin/bash

sum=0

for i in "$@"
do
	sum=$((sum + i))
	echo $i | grep "^[a-zA-Z]" > /dev/null
       
	if [ $? -eq 0 ]; then
		echo "Sorry, '$i' is not a number"
		exit 1
	fi
      	


done


echo $sum
